### ISSUE TITLE
Step "cleanup journalctl logs" is skipped on some Debian armv7 installation

### ISSUE THREAD

**Issue by pixrl** [robertdebock/ansible-role-maintenance#1]
## Describe the bug

It seems like `cleanup journalctl logs` is skipped on some armv7 installations. Right now I am using those roles on Beaglebone and Armbian odroid SoCs and it seems like `journalctl` path is different on beaglebone `armv7` debian vs odroid `arm64` armbian.

```
root@armbian:~# which journalctl 
/usr/bin/journalctl
```
```
root@beaglebone:~# which journalctl 
/bin/journalctl
```

It seems like the problem is this stat:
```
- name: check journalctl
  ansible.builtin.stat:
    path: /usr/bin/journalctl
  register: maintenance_journalctl
```

On beaglebone armv7 Debian there is no `/usr/bin/journalctl`
```
root@beaglebone:~# stat /usr/bin/journalctl
stat: cannot statx '/usr/bin/journalctl': No such file or directory
```

## Playbook

`requirements.yml`
```yaml
---
collections:
  - name: community.general
  - name: ansible.posix
roles:
  - name: robertdebock.update_package_cache
    src: https://github.com/robertdebock/ansible-role-update_package_cache.git
    version: 2.1.2
  - name: robertdebock.update
    src: https://github.com/robertdebock/ansible-role-update
    version: 3.1.4
  - name: robertdebock.maintenance
    src: https://github.com/robertdebock/ansible-role-maintenance.git
    version: 2.1.4
```
`playbooks/maintenance.yml`
```
- name: Perform maintenance
  hosts: all
  become: yes
  roles:
    - { role: robertdebock.maintenance }
    - { role: robertdebock.update }

```

```yaml
ansible-playbook playbooks/maintenance.yml
```

## Output

```
TASK [robertdebock.maintenance : check journalctl] ************************************************************************
ok: [beaglebone-debian.lan]
ok: [beaglebone-debian.lan]
ok: [armbian-debian.lan]
ok: [armbian-debian.lan]

TASK [robertdebock.maintenance : cleanup journalctl logs] *****************************************************************
skipping: [beaglebone-debian.lan]
skipping: [beaglebone-debian.lan]
ok: [armbian-debian.lan]
ok: [armbian-debian.lan]
```

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)

```
root@control ~/ $ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
...
```
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
```
ansible [core 2.13.3]
...
  executable location = /usr/sbin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
  jinja version = 3.0.3
  libyaml = True
```
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)

`Beaglebone node`:
```
root@beaglebone:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
`Armbian node`:
```
root@armbian:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
